# Generated by Django 2.2.6 on 2019-10-07 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magicscraper', '0002_auto_20190910_0654'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('scryfallId', models.UUIDField()),
                ('oracleId', models.UUIDField(blank=True)),
                ('uri', models.CharField(blank=True, max_length=1000)),
                ('scryfallUri', models.CharField(blank=True, max_length=1000)),
                ('name', models.CharField(max_length=1000)),
                ('cmc', models.IntegerField(blank=True)),
                ('typeLine', models.CharField(blank=True, max_length=1000)),
                ('oracleText', models.CharField(blank=True, max_length=1000)),
                ('manaCost', models.CharField(blank=True, max_length=1000)),
                ('colors', models.TextField(blank=True)),
                ('colorIdentity', models.TextField(blank=True)),
                ('collectorNumber', models.CharField(blank=True, max_length=1000)),
                ('imageLinks', models.TextField(blank=True)),
                ('rarity', models.CharField(blank=True, max_length=1000)),

            ],
        ),
    ]
