# Generated by Django 2.2.6 on 2019-10-07 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magicscraper', '0003_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='editionCode',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='card',
            name='editionName',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
