# Generated by Django 2.2.6 on 2019-10-07 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magicscraper', '0005_auto_20191007_1224'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='setCode',
            new_name='editionCode',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='setName',
            new_name='editionName',
        ),
    ]
