# Generated by Django 2.2.6 on 2019-10-07 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magicscraper', '0006_auto_20191007_1226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='collectorNumber',
        ),
    ]
