# Generated by Django 2.2.6 on 2019-10-07 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magicscraper', '0007_remove_card_collectornumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='collectorNumber',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
