# Generated by Django 2.2.6 on 2019-10-07 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magicscraper', '0009_card_tcgprice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='editionCode',
            new_name='set',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='editionName',
            new_name='setName',
        ),
    ]
