# Generated by Django 2.2.6 on 2019-10-08 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magicscraper', '0010_auto_20191007_1254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='set',
        ),
    ]
