# Generated by Django 2.2.6 on 2019-10-08 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magicscraper', '0011_remove_card_set'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='setName',
        ),
    ]
