# Generated by Django 2.2.6 on 2019-10-08 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magicscraper', '0013_auto_20191008_0508'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='smallImage',
            field=models.TextField(blank=True),
        ),
    ]
