# Generated by Django 2.2.6 on 2019-10-08 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magicscraper', '0014_card_smallimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='smallImage',
            field=models.TextField(blank=True, null=True),
        ),
    ]
