# Generated by Django 2.2.6 on 2019-10-08 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magicscraper', '0015_auto_20191008_0550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='scryfallId',
            field=models.UUIDField(null=True),
        ),
    ]
