# Generated by Django 2.2.6 on 2019-10-08 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magicscraper', '0016_auto_20191008_0553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='imageLinks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
