# Generated by Django 2.2.6 on 2019-10-08 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magicscraper', '0017_auto_20191008_0554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='colorIdentity',
            field=models.TextField(blank=True, null=True),
        ),
    ]
