# Generated by Django 2.2.6 on 2019-10-08 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magicscraper', '0018_auto_20191008_0558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='oracleText',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
